openapi: 3.0.3
info:
  title: Swagger Playa Test
  description: |-
    This is a simple Users API Documentation page using Swagger
  contact:
    email: vladvisinescu@gmail.com
  version: 0.0.1
tags:
  - name: user
    description: Operations about user
paths:
  /api/users:
    get:
      tags:
        - user
      summary: Finds Using using filters
      description: This endpoint accepts multiple filters

      parameters:
        - name: is_active
          in: query
          description: Status of the active state of user
          required: false
          example: 0
          schema:
            type: integer
            enum:
              - 0
              - 1
        - name: is_member
          in: query
          description: Status of the membership state of user
          required: false
          example: 1
          schema:
            type: integer
            enum:
              - 0
              - 1
        - name: last_login_at
          in: query
          description: Date range for Last Login date
          required: false
          schema:
            type: object
            properties:
              start:
                type: string
                format: date-time
                example: '2020-01-01 00:00:00'
              end:
                type: string
                format: date-time
                example: '2023-12-31 00:00:00'
        - name: user_type
          in: query
          example: [1, 3]
          description: Filter for any of the provided user types
          required: false
          schema:
            type: array
            items:
              type: integer
              format: integer[]
              enum:
                - 1
                - 2
                - 3
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                properties:
                  data:
                    type: array
                    items:
                      allOf:
                        - $ref: '#/components/schemas/User'
        '400':
          description: Invalid status value
components:
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
          example: test_206_user
        email:
          type: string
          example: test_206@tnc.com
        is_active:
          type: boolean
          example: true
        is_member:
          type: boolean
          example: false
        last_login_at:
          type: string
          format: date-time
          example: '2022-02-15 05:35:29'
        user_type:
          type: integer
          enum: [1, 2, 3]
          example: 1
